#pragma once

//#define DISABLE_CUSTOM_ALLOCATORS
//#define DISABLE_FRAME_ALLOCATOR
//#define DISABLE_POOL_ALLOCATOR

#ifdef DISABLE_CUSTOM_ALLOCATORS
#define DISABLE_FRAME_ALLOCATOR
#define DISABLE_POOL_ALLOCATOR
#endif